# Generated by Django 5.2.4 on 2025-07-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('picture', models.ImageField(null=True, upload_to='static/gallery/')),
                ('language', models.CharField(max_length=70, null=True)),
            ],
        ),
    ]
