# Generated by Django 5.2.4 on 2025-07-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tblteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchname', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblregister',
            fields=[
                ('name', models.CharField(max_length=70, null=True)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/userpic/')),
                ('batch', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(null=True)),
                ('regdate', models.DateField(null=True)),
            ],
        ),
    ]
