# Generated by Django 5.2.4 on 2025-08-01 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_mylecture_mytask_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mytask',
            old_name='taskfile',
            new_name='task_file',
        ),
    ]
