# Generated by Django 5.2.4 on 2025-08-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_taskfile_mytask_task_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notes_file',
            field=models.FileField(blank=True, null=True, upload_to='static/notes/'),
        ),
    ]
