# Generated by Django 5.2.4 on 2025-08-02 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_notes_notes_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytask',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='batch',
        ),
        migrations.DeleteModel(
            name='mylecture',
        ),
        migrations.DeleteModel(
            name='mytask',
        ),
        migrations.DeleteModel(
            name='notes',
        ),
    ]
