# Generated by Django 5.2.4 on 2025-08-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_mylecture_mytask_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='submittedtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, null=True)),
                ('tid', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=50, null=True)),
                ('marks', models.IntegerField(null=True)),
                ('upload_task', models.FileField(blank=True, null=True, upload_to='static/submitted/')),
            ],
        ),
        migrations.RemoveField(
            model_name='mytask',
            name='upload_task',
        ),
    ]
